---
title: "InfluNet"

author:
  - Luca Cozzuto^[CRG, luca.cozzuto@crg.eu]
  - Francesco Branda^[Unical, francesco.branda@unical.it]

site: bookdown::InfluNet
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
---

# Season 2012 / 2013


```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2012 <- "flu-season/2012-2013/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2012, "2012 / 2013", "Total samples")

```

# Season 2013 / 2014


```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2013 <- "flu-season/2013-2014/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2013, "2013 / 2014", "Total samples")

```


# Season 2014 / 2015


```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2014 <- "flu-season/2014-2015/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2014, "2014 / 2015", "Total samples")

```


# Season 2015 / 2016


```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2015 <- "flu-season/2015-2016/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2015, "2015 / 2016", "Total samples")

```

# Season 2016 / 2017


```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2016 <- "flu-season/2016-2017/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2016, "2016 / 2017", "Total samples")

```


# Season 2017 / 2018


```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2017 <- "flu-season/2017-2018/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2017, "2017 / 2018", "Total samples")

```

# Season 2018 / 2019

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2018 <- "flu-season/2018-2019/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2018, "2018 / 2019", "Samples analyzed")


```

# Season 2019 / 2020

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2019 <- "flu-season/2019-2020/virological_data/national_typing_subtyping_influenza_viruses.csv"


source("functions.R", local = knitr::knit_global())

makePlotFlu(ita_2019, "2019 / 2020", "Samples analyzed")

```

# Season 2020 / 2021

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}


ita_2020 <- "flu-season/2020-2021/virological_data/national_typing_subtyping_influenza_viruses.csv"
cases_web <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
death_web <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"


source("functions.R", local = knitr::knit_global())

makePlotCovid(death_web, cases_web, ita_2020, "2020 / 2021", pal1)

```

# Season 2021 / 2022

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}

ita_2021 <- "flu-season/2021-2022/virological_data/national_typing_subtyping_influenza_viruses.csv"
cases_web <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
death_web <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"


source("functions.R", local = knitr::knit_global())

makePlotCovid(death_web, cases_web, ita_2021, "2021 / 2022", pal1)
```

# Season 2022 / 2023

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}

ita_2022 <- "flu-season/2022-2023/virological_data/national_typing_subtyping_influenza_viruses.csv"
cases_web <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
death_web <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"


source("functions.R", local = knitr::knit_global())

makePlotCovid(death_web, cases_web, ita_2022, "2022 / 2023", pal2)
```

# Influenza like illness 

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}
path<-"flu-season/"

histILIdata<-getILIHistoricalData(path)
makePlotIliHistory(histILIdata)

```

# Comparison Flu A

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}
path<-"flu-season/"

source("functions.R", local = knitr::knit_global())

histdata<-getFluHistoricalData(path)
makePlotFluHistory(histdata, "FLU A", "#f6e8e8", "red")

```

# Comparison Flu B

```{r echo=FALSE, warning = FALSE, message=FALSE, fig.width=7}
path<-"flu-season/"

source("functions.R", local = knitr::knit_global())

histdata<-getFluHistoricalData(path)
makePlotFluHistory(histdata, "FLU B", "powderblue", "blue")

```



